# config.py
from pathlib import Path

BASE_ELO = 1500
K = 20
HOME_ADVANTAGE = 65

APP_DIR = Path(__file__).resolve().parent
LOGOS_DIR = APP_DIR / "Logos"
SHIELD_IMAGE_PATH = APP_DIR / "Shield.png"
NFL_IMAGE_PATH = APP_DIR / "NFL.png"

EXCEL_FILE = "games.xlsx"
HIST_SHEET = "games"
SCHEDULE_SHEET = "2025 schedule"

DEFAULT_BANKROLL = 50

NFL_FULL_NAMES = {
    "ARI": "Arizona Cardinals",
    "ATL": "Atlanta Falcons",
    "BAL": "Baltimore Ravens",
    "BUF": "Buffalo Bills",
    "CAR": "Carolina Panthers",
    "CHI": "Chicago Bears",
    "CIN": "Cincinnati Bengals",
    "CLE": "Cleveland Browns",
    "DAL": "Dallas Cowboys",
    "DEN": "Denver Broncos",
    "DET": "Detroit Lions",
    "GB": "Green Bay Packers",
    "HOU": "Houston Texans",
    "IND": "Indianapolis Colts",
    "JAX": "Jacksonville Jaguars",
    "KC": "Kansas City Chiefs",
    "LV": "Las Vegas Raiders",
    "LAC": "Los Angeles Chargers",
    "LA": "Los Angeles Rams",
    "MIA": "Miami Dolphins",
    "MIN": "Minnesota Vikings",
    "NE": "New England Patriots",
    "NO": "New Orleans Saints",
    "NYG": "New York Giants",
    "NYJ": "New York Jets",
    "PHI": "Philadelphia Eagles",
    "PIT": "Pittsburgh Steelers",
    "SF": "San Francisco 49ers",
    "SEA": "Seattle Seahawks",
    "TB": "Tampa Bay Buccaneers",
    "TEN": "Tennessee Titans",
    "WAS": "Washington Commanders",
}

TEAM_COLORS = {
    "ARI": "#97233F",
    "ATL": "#A71930",
    "BAL": "#241773",
    "BUF": "#00338D",
    "CAR": "#0085CA",
    "CHI": "#0B162A",
    "CIN": "#FB4F14",
    "CLE": "#311D00",
    "DAL": "#003594",
    "DEN": "#FB4F14",
    "DET": "#0076B6",
    "GB": "#203731",
    "HOU": "#03202F",
    "IND": "#002C5F",
    "JAX": "#006778",
    "KC": "#E31837",
    "LV": "#000000",
    "LAC": "#0080C6",
    "LA": "#003594",
    "MIA": "#008E97",
    "MIN": "#4F2683",
    "NE": "#002244",
    "NO": "#D3BC8D",
    "NYG": "#0B2265",
    "NYJ": "#125740",
    "PHI": "#004C54",
    "PIT": "#FFB612",
    "SF": "#AA0000",
    "SEA": "#002244",
    "TB": "#D50A0A",
    "TEN": "#0C2340",
    "WAS": "#5A1414",
}

TEAM_NAME_FIXES = {
    "Clevland Browns": "Cleveland Browns",
    "NY Jets": "New York Jets",
    "NY Giants": "New York Giants",
    "Jags": "Jacksonville Jaguars",
}

ESPN_TEAM_IDS = {
    "ARI": 22,
    "ATL": 1,
    "BAL": 33,
    "BUF": 2,
    "CAR": 29,
    "CHI": 3,
    "CIN": 4,
    "CLE": 5,
    "DAL": 6,
    "DEN": 7,
    "DET": 8,
    "GB": 9,
    "HOU": 34,
    "IND": 11,
    "JAX": 30,
    "KC": 12,
    "LV": 13,
    "LAC": 24,
    "LA": 14,
    "MIA": 15,
    "MIN": 16,
    "NE": 17,
    "NO": 18,
    "NYG": 19,
    "NYJ": 20,
    "PHI": 21,
    "PIT": 23,
    "SF": 25,
    "SEA": 26,
    "TB": 27,
    "TEN": 10,
    "WAS": 28,
}

STADIUMS = {
    "Arizona Cardinals": {"stadium": "State Farm Stadium", "city": "Glendale", "state": "Arizona", "lat": 33.5276, "lon": -112.2626},
    "Atlanta Falcons": {"stadium": "Mercedes-Benz Stadium", "city": "Atlanta", "state": "Georgia", "lat": 33.7554, "lon": -84.4008},
    "Baltimore Ravens": {"stadium": "M&T Bank Stadium", "city": "Baltimore", "state": "Maryland", "lat": 39.2780, "lon": -76.6227},
    "Buffalo Bills": {"stadium": "Highmark Stadium", "city": "Orchard Park", "state": "New York", "lat": 42.7738, "lon": -78.7869},
    "Carolina Panthers": {"stadium": "Bank of America Stadium", "city": "Charlotte", "state": "North Carolina", "lat": 35.2251, "lon": -80.8531},
    "Chicago Bears": {"stadium": "Soldier Field", "city": "Chicago", "state": "Illinois", "lat": 41.8623, "lon": -87.6167},
    "Cincinnati Bengals": {"stadium": "Paycor Stadium", "city": "Cincinnati", "state": "Ohio", "lat": 39.0954, "lon": -84.5161},
    "Cleveland Browns": {"stadium": "Cleveland Browns Stadium", "city": "Cleveland", "state": "Ohio", "lat": 41.5061, "lon": -81.6995},
    "Dallas Cowboys": {"stadium": "AT&T Stadium", "city": "Arlington", "state": "Texas", "lat": 32.7473, "lon": -97.0945},
    "Denver Broncos": {"stadium": "Empower Field at Mile High", "city": "Denver", "state": "Colorado", "lat": 39.7439, "lon": -105.0201},
    "Detroit Lions": {"stadium": "Ford Field", "city": "Detroit", "state": "Michigan", "lat": 42.3400, "lon": -83.0456},
    "Green Bay Packers": {"stadium": "Lambeau Field", "city": "Green Bay", "state": "Wisconsin", "lat": 44.5013, "lon": -88.0622},
    "Houston Texans": {"stadium": "NRG Stadium", "city": "Houston", "state": "Texas", "lat": 29.6847, "lon": -95.4107},
    "Indianapolis Colts": {"stadium": "Lucas Oil Stadium", "city": "Indianapolis", "state": "Indiana", "lat": 39.7601, "lon": -86.1639},
    "Jacksonville Jaguars": {"stadium": "EverBank Stadium", "city": "Jacksonville", "state": "Florida", "lat": 30.3240, "lon": -81.6376},
    "Kansas City Chiefs": {"stadium": "GEHA Field at Arrowhead Stadium", "city": "Kansas City", "state": "Missouri", "lat": 39.0490, "lon": -94.4839},
    "Las Vegas Raiders": {"stadium": "Allegiant Stadium", "city": "Paradise", "state": "Nevada", "lat": 36.0909, "lon": -115.1830},
    "Los Angeles Chargers": {"stadium": "SoFi Stadium", "city": "Inglewood", "state": "California", "lat": 33.9535, "lon": -118.3387},
    "Los Angeles Rams": {"stadium": "SoFi Stadium", "city": "Inglewood", "state": "California", "lat": 33.9535, "lon": -118.3387},
    "Miami Dolphins": {"stadium": "Hard Rock Stadium", "city": "Miami Gardens", "state": "Florida", "lat": 25.9580, "lon": -80.2389},
    "Minnesota Vikings": {"stadium": "U.S. Bank Stadium", "city": "Minneapolis", "state": "Minnesota", "lat": 44.9737, "lon": -93.2570},
    "New England Patriots": {"stadium": "Gillette Stadium", "city": "Foxborough", "state": "Massachusetts", "lat": 42.0909, "lon": -71.2643},
    "New Orleans Saints": {"stadium": "Caesars Superdome", "city": "New Orleans", "state": "Louisiana", "lat": 29.9509, "lon": -90.0815},
    "New York Giants": {"stadium": "MetLife Stadium", "city": "East Rutherford", "state": "New Jersey", "lat": 40.8135, "lon": -74.0745},
    "New York Jets": {"stadium": "MetLife Stadium", "city": "East Rutherford", "state": "New Jersey", "lat": 40.8135, "lon": -74.0745},
    "Philadelphia Eagles": {"stadium": "Lincoln Financial Field", "city": "Philadelphia", "state": "Pennsylvania", "lat": 39.9008, "lon": -75.1675},
    "Pittsburgh Steelers": {"stadium": "Acrisure Stadium", "city": "Pittsburgh", "state": "Pennsylvania", "lat": 40.4468, "lon": -80.0158},
    "San Francisco 49ers": {"stadium": "Levi's Stadium", "city": "Santa Clara", "state": "California", "lat": 37.4030, "lon": -121.9700},
    "Seattle Seahawks": {"stadium": "Lumen Field", "city": "Seattle", "state": "Washington", "lat": 47.5952, "lon": -122.3316},
    "Tampa Bay Buccaneers": {"stadium": "Raymond James Stadium", "city": "Tampa", "state": "Florida", "lat": 27.9759, "lon": -82.5033},
    "Tennessee Titans": {"stadium": "Nissan Stadium", "city": "Nashville", "state": "Tennessee", "lat": 36.1665, "lon": -86.7713},
    "Washington Commanders": {"stadium": "Commanders Field", "city": "Landover", "state": "Maryland", "lat": 38.9077, "lon": -76.8645},
}

__all__ = [
    "BASE_ELO",
    "K",
    "HOME_ADVANTAGE",
    "APP_DIR",
    "LOGOS_DIR",
    "SHIELD_IMAGE_PATH",
    "NFL_IMAGE_PATH",
    "EXCEL_FILE",
    "HIST_SHEET",
    "SCHEDULE_SHEET",
    "DEFAULT_BANKROLL",
    "NFL_FULL_NAMES",
    "TEAM_COLORS",
    "TEAM_NAME_FIXES",
    "ESPN_TEAM_IDS",
    "STADIUMS",
]
